src/main/java/lt/vtvpmc/exam/entities/Client.java
package lt.vtvpmc.exam.entities;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


@Entity
public class Client implements Serializable {
    
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    
    private String firstName;
    
    private String lastName;
    
    private String phoneNumber;

    public Client() {
    }

    public Client(String firstName, String lastName, String phoneNumber) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
    }
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    
    
}

src/main/java/lt/vtvpmc/exam/ui/ClientListBean.java
package lt.vtvpmc.exam.ui;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import lt.vtvpmc.exam.entities.Client;
import org.springframework.transaction.annotation.Transactional;

/**
 *
 * @author giedrius
 */
public class ClientListBean {
    
    @PersistenceContext
    private EntityManager entityManager;
    
    @Transactional(readOnly = true)
    public List<Client> getClientList() {
        Query q = entityManager.createQuery("select c from Client c");
        return q.getResultList();
    }
    
    @Transactional
    public void removeClient(Client client) {
        entityManager.remove(entityManager.merge(client));
    }
    
}

src/main/java/lt/vtvpmc/exam/ui/NewClientBean.java
package lt.vtvpmc.exam.ui;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import lt.vtvpmc.exam.entities.Client;
import org.springframework.transaction.annotation.Transactional;



public class NewClientBean {
    
    @PersistenceContext
    private EntityManager entityManager;
    
    private String clientFirstName;
    private String clientLastName;
    private String clientPhoneNumber;
    
    @Transactional
    public String save() {
        Client client = new Client(clientFirstName, clientLastName, clientPhoneNumber);
        entityManager.persist(client);
        return "main";
    }
    
    public String getClientFirstName() {
        return clientFirstName;
    }

    public void setClientFirstName(String clientFirstName) {
        this.clientFirstName = clientFirstName;
    }

    public String getClientLastName() {
        return clientLastName;
    }

    public void setClientLastName(String clientLastName) {
        this.clientLastName = clientLastName;
    }

    public String getClientPhoneNumber() {
        return clientPhoneNumber;
    }

    public void setClientPhoneNumber(String clientPhoneNumber) {
        this.clientPhoneNumber = clientPhoneNumber;
    }
    

    
}

src/main/webapp/addNewCustomer.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Add New Customer</title>
    </h:head>
    
    <h:body>
        <h:form id="newCustomerForm">
            <h3>Add New Client</h3>
            <h:panelGrid columns="3">
                <h:outputText value="Name:"/>
                <h:inputText id="clientName" value="#{newClientBean.clientFirstName}" required="true"/>
                <h:message for="clientName"/>
                
                <h:outputText value="Surname:"/>
                <h:inputText id="clientSurname" value="#{newClientBean.clientLastName}" required="true"/>
                <h:message for="clientSurname"/>
                
                <h:outputText value="Phone #:"/>
                <h:inputText id="clientPhoneNo" value="#{newClientBean.clientPhoneNumber}" required="true"/>
                <h:message for="clientPhoneNo"/>
            </h:panelGrid>
            <h:commandButton action="#{newClientBean.save()}" value="Add"/>
        </h:form>
    </h:body>
</html>

src/main/webapp/main.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    
    <h:head>
        <title>Main</title>
        <h:outputStylesheet name="styles.css"/>
    </h:head>

    <h:body>
        <h:form id="tableActionForm">
            <h:dataTable value="#{clientListBean.clientList}" var="client">
                <h:column>
                    <f:facet name="header">
                        First Name
                    </f:facet>
                    <h:outputText value="#{client.firstName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Last Name
                    </f:facet>
                    <h:outputText value="#{client.lastName}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Actions
                    </f:facet>
                    <h:commandLink actionListener="#{clientListBean.removeClient(client)}" value="Delete"/>
                </h:column>
            </h:dataTable>
        </h:form>

        <h:form id="actionForm">
            <h:commandButton id="addNewCustomerBtn" action="addNewCustomer" value="Add New Customer"/>
        </h:form>

    </h:body>
</html>